name: Update README

on:
  push:
    branches:
      - main  # Укажите вашу основную ветку

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update README.md
      run: |
        echo "## Soulless Coffee" >> README.md
        echo "<a href=\"https://discord.gg/ZSUpv25GRz\"><img src=\"https://img.shields.io/discord/907577663810576405.svg?style=flat&label=Join%20Community&color=7289DA\" alt=\"Join Community Badge\"/></a>" >> README.md

    - name: Commit changes
      run: |
        git config --local user.email "cookiekomori@outlook.com"  # Укажите ваш email
        git config --local user.name "cookiiekomori"  # Укажите ваше имя
        git add README.md
        git commit -m "Update README.md" || echo "No changes to commit"

    - name: Push changes
      run: git push
